name: Build and check
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: 8

            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install build dependencies
              run: pnpm install

            - name: Run lint
              run: pnpm lint

            - name: Run build
              run: pnpm run build
